version: "3"
services:
  db:
    container_name: motorbikes_db 
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: motorbikes_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
  php:
    container_name: motorbikes_php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
   driver: local